### ISSUE TITLE
[BUG] Unable to create tmp directory for int based unique IDs

### ISSUE THREAD

**Issue by smallcoderhujin** [arabcoders/ytptube#115]
**Describe the bug**
![image](https://github.com/user-attachments/assets/eed38591-f239-4669-bde5-f10b04056d1a)

**To Reproduce**
download video: https://m.ximalaya.com/album/81894933

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/eed38591-f239-4669-bde5-f10b04056d1a)

**Additional context**

**Comment by arabcoders** [comment]
Hello, Thank you for your report, it has been fixed.
