### ISSUE TITLE
[BUG] Not able to download videos (No Video format found)

### ISSUE THREAD

**Issue by lucabmn** [arabcoders/ytptube#153]
**Describe the bug**
I'm not able to download any video's.

**To Reproduce**
Fresh installation with the default docker-compose.yml without any configuration.

**Additional context**
[youtube] TluZCovv2KY: No video formats found!; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

**Comment by arabcoders** [comment]
we recently added new default preset this might be the problem, can you try selecting different preset and see if this fixes tour problem?

**Comment by arabcoders** [comment]
I ran the exact command in README.md and i was able to download as usual with all presets except the audio which has known problem with youtube right now.

![{28F9A49F-F664-447A-8E15-5CC6F373D102}](https://github.com/user-attachments/assets/091a169c-b723-4514-8500-ae2189a10f40)

if you are facing 403: forbbiden you are probably hit by this [yt-dlp issue](https://github.com/yt-dlp/yt-dlp/issues/11868)

**Comment by arabcoders** [comment]
@lucabmn any updates?

**Comment by arabcoders** [comment]
Seems to have been user issue, as there is no response in 5days. feel free to re-open the issue if you still have a problem.
