### ISSUE TITLE
[BUG]The output format cannot output the download time normally.

### ISSUE THREAD

**Issue by 2284787774** [arabcoders/ytptube#95]
**Describe the bug**
Unable to output download time through output format configuration.
![微信截图_20240517141725](https://github.com/arabcoders/ytptube/assets/26424174/cb015412-fc13-4d2a-ad60-65c31558ac9d)
![微信截图_20240517141823](https://github.com/arabcoders/ytptube/assets/26424174/6e75dde1-b58f-41e5-8c50-7689a0e2606d)

**To Reproduce**
You can obtain it normally using the yt-dlp command line
![微信截图_20240517141550](https://github.com/arabcoders/ytptube/assets/26424174/664fc67e-1b7f-46e2-ade5-97274c26ae80)
![微信截图_20240517141609](https://github.com/arabcoders/ytptube/assets/26424174/c18eb350-7821-42b8-a700-a6ba1bd17a66)

**Expected behavior**
Name the live broadcast file using the title + download time format

**Comment by arabcoders** [comment]
Hi,

You are attempting to use dash script in the output format which isn't supported in the embedded yt-dlp library. Try this for date `%(release_date>%Y%m%d,upload_date>%Y%m%d)s` i am sure there is probably more fields i am not covering which you can get by dumping using --dump-json

**Comment by 2284787774** [comment]
> Hi,
> 
> You are attempting to use bash script in the output format which isn't supported in the embedded yt-dlp library. Try this for date `%(release_date>%Y%m%d,upload_date>%Y%m%d)s` i am sure there is probably more fields i am not covering which you can get by dumping using --dump-json

Hello, because I downloaded the live broadcast without the upload date, using %(upload_date>%Y-%m-%d)s.%(ext)s will only get NA.
![微信截图_20240517152435](https://github.com/arabcoders/ytptube/assets/26424174/ce9f9a8f-bb6d-4cef-ab85-64551453b55b)

**Comment by arabcoders** [comment]
> > Hi,
> 
> > 
> 
> > You are attempting to use bash script in the output format which isn't supported in the embedded yt-dlp library. Try this for date `%(release_date>%Y%m%d,upload_date>%Y%m%d)s` i am sure there is probably more fields i am not covering which you can get by dumping using --dump-json
> 
> 
> 
> Hello, because I downloaded the live broadcast without the upload date, using %(upload_date>%Y-%m-%d)s.%(ext)s will only get NA.
> 
> ![微信截图_20240517152435](https://github.com/arabcoders/ytptube/assets/26424174/ce9f9a8f-bb6d-4cef-ab85-64551453b55b)
> 
> 

Thanks for the clarification. can you share json dump of the request? 

Because as things stand i don't see yt-dlp to ever support bash scripts in the future as its cross platform tool. We may probably provide some string interpolation for date i.e `{date:format}` and intercept them before reaching yt-dlp

**Comment by 2284787774** [comment]
> --dump-json

Sorry, I don't know how --dump-json should be used, maybe I can give you rtmp link to test

rtmp://xt3jtpm4koufnwht.7kv5kqq7k77g.hebeisaixin.com/live/1722562749?token=b5950a9019f3ce49652d67aa2de535f3&t=1716017507

**Comment by 2284787774** [comment]
> > > 你好，
> > 
> > 
> > > 
> > 
> > 
> > > 您正在尝试以嵌入式 yt-dlp 库不支持的输出格式使用 bash 脚本。尝试一下这个日期，`%(release_date>%Y%m%d,upload_date>%Y%m%d)s`我确信可能还有更多我没有涵盖的字段，您可以通过使用 --dump-json 转储来获得这些字段
> > 
> > 
> > 您好，因为我下载的直播没有上传日期，所以使用 %(upload_date>%Y-%m-%d)s.%(ext)s 只会得到 NA。
> > ![微信截图_20240517152435](https://private-user-images.githubusercontent.com/26424174/331502052-ce9f9a8f-bb6d-4cef-ab85-64551453b55b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzE0NzEsIm5iZiI6MTcxNTkzMTE3MSwicGF0aCI6Ii8yNjQyNDE3NC8zMzE1MDIwNTItY2U5ZjlhOGYtYmI2ZC00Y2VmLWFiODUtNjQ1NTE0NTNiNTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA3MzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NGU1YTUyMzZiZDFkMGMxZWZjOTJhNjlhN2I3YzU5YWUzOWY4MDVmZDVmMDNkMWJlODdhMGI0MTNlNDdhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ivhW12biPYgGDaKkzwZX3d7BPbp7JpHc7XgBOP5Y83I)
> 
> 感谢您的澄清。你能分享请求的 json 转储吗？
> 
> 因为就目前情况而言，我不认为 yt-dlp 将来会支持 bash 脚本作为其跨平台工具。我们可能会为日期提供一些字符串插值，`{date:format}`并在到达 yt-dlp 之前拦截它们

Sorry, I don't know how --dump-json should be used, maybe I can give you rtmp link to test

rtmp://xt3jtpm4koufnwht.7kv5kqq7k77g.hebeisaixin.com/live/1722562749?token=b5950a9019f3ce49652d67aa2de535f3&t=1716017507

**Comment by arabcoders** [comment]
Thanks i tested the link

it has `epoch` field which in theory should function as date function for when the file was downloaded try this

`(epoch>%Y%m%d)s` if this also doesn't work i will have to implement what i mentioned earlier which will take sometime. probably at the end of today.

**Comment by 2284787774** [comment]
> 谢谢我测试了链接
> 
> 它有`epoch`一个字段，理论上应该充当文件下载时的日期函数，试试这个
> 
> `%(epoch>%Y%m%d)s`如果这也不起作用，我将不得不实施我之前提到的内容，这将需要一些时间。可能在今天结束时。

Thank you very much, it successfully got the date. But when I changed it to %(epoch>%Y%m%d-%H%M%S)s, the hours, minutes and seconds it got were 8 hours different from my local time. Maybe it's a problem with the live broadcast server
![微信截图_20240517160845](https://github.com/arabcoders/ytptube/assets/26424174/b99c1c00-8e88-42b3-a704-fa1dcc7554f7)

**Comment by arabcoders** [comment]
thats probably because the timezone isn't set correctly and sadly we don't expose it yet in the future builds you should be able to change it via a environment variable.
